namespace Supprocom.NativeAllocationManagement.Demos.VoxelChunkPipeline.SharedContract;

public readonly record struct CorrectnessReport(
    bool Passed,
    PipelineResult Safe,
    PipelineResult Nam,
    bool PayloadObjectParity);

public readonly record struct PairedSample(int Pair, ChildRunResult Safe, ChildRunResult Nam);

public readonly record struct BenchmarkReport(
    DateTime UtcStarted,
    VoxelWorkloadOptions Workload,
    int PairedRuns,
    int WarmupChunksPerWorker,
    string ConfidenceMethod,
    bool CorrectnessPassed,
    IReadOnlyList<PairedSample> Samples,
    BenchmarkSummary Summary);

public readonly record struct BenchmarkSummary(
    bool CorrectnessPassed,
    bool GatePassed,
    double SafeMeanMilliseconds,
    double NamMeanMilliseconds,
    double SafeLatencyStandardDeviation,
    double NamLatencyStandardDeviation,
    double SafeMeanThroughput,
    double NamMeanThroughput,
    double MeanPairedSpeedup,
    double PairedSpeedupStandardDeviation,
    double StudentT95Critical,
    double PairedSpeedupConfidenceLower95,
    double PairedSpeedupConfidenceUpper95,
    double SafeMeanManagedAllocatedBytes,
    double NamMeanManagedAllocatedBytes,
    double SafeMeanColdManagedAllocatedBytes,
    double NamMeanColdManagedAllocatedBytes,
    double SafeMeanColdManagedBackingBytes,
    double NamMeanColdManagedBackingBytes,
    bool MaterialManagedAllocationReduction,
    bool WarmManagedAllocationReduction,
    bool ThroughputGate,
    bool ConfidenceGate,
    double SafeP50Milliseconds,
    double SafeP95Milliseconds,
    double SafeP99Milliseconds,
    double NamP50Milliseconds,
    double NamP95Milliseconds,
    double NamP99Milliseconds,
    double SafeMeanGen0Collections,
    double SafeMeanGen1Collections,
    double SafeMeanGen2Collections,
    double NamMeanGen0Collections,
    double NamMeanGen1Collections,
    double NamMeanGen2Collections,
    double SafeMeanHeapBytesAfterRun,
    double NamMeanHeapBytesAfterRun,
    double? SafeMeanLargeObjectHeapBytesAfterRun,
    double? NamMeanLargeObjectHeapBytesAfterRun,
    double SafeMeanPeakWorkingSetBytes,
    double NamMeanPeakWorkingSetBytes,
    double SafeMeanPeakManagedBackingBytes,
    double NamMeanPeakManagedBackingBytes,
    double NamMeanPeakNativeBackingBytes,
    double NamMeanPeakRetainedNativeBackingBytes,
    double NamMeanFinalNativeBackingBytes,
    double SafeMeanCoordinateStageBytes,
    double SafeMeanFaceStageBytes,
    double SafeMeanPackingStageBytes,
    double NamMeanCoordinateStageBytes,
    double NamMeanFaceStageBytes,
    double NamMeanPackingStageBytes,
    double NamMeanLeaseCount,
    double NamMeanScopedRecycleCount,
    double NamMeanClearedBytes,
    double NamMeanReusedNativeSegmentCount,
    double NamMeanReclaimedRangeReuseCount,
    double NamMeanReclaimedRangeReuseBytes,
    double NamMeanGenerationMilliseconds,
    double NamMeanFaceDerivationMilliseconds,
    double NamMeanTransparentMaskMilliseconds,
    double NamMeanOpaquePackingMilliseconds,
    double NamMeanTransparentPackingMilliseconds,
    double NamMeanCoordinateRecycleMilliseconds,
    double NamMeanFaceRecycleMilliseconds,
    double NamMeanMaskRecycleMilliseconds,
    double NamMeanPackingRecycleMilliseconds,
    double? SafeMeanGenerationMilliseconds = null,
    double? SafeMeanFaceDerivationMilliseconds = null,
    double? SafeMeanTransparentMaskMilliseconds = null,
    double? SafeMeanOpaquePackingMilliseconds = null,
    double? SafeMeanTransparentPackingMilliseconds = null,
    double? SafeMeanCoordinateRecycleMilliseconds = null,
    double? SafeMeanFaceRecycleMilliseconds = null,
    double? SafeMeanMaskRecycleMilliseconds = null,
    double? SafeMeanPackingRecycleMilliseconds = null,
    double? SafeMeanColdElapsedMilliseconds = null,
    double? NamMeanColdElapsedMilliseconds = null);
